/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pl.zajacp

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        assertNotNull(App(), "app should have a greeting")
    }
}
