/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pl.zajacp

import com.google.gson.Gson
import getValuesFromRange
import org.apache.http.util.Args

class App {
    companion object {
        private val gson = Gson()

        @JvmStatic
        fun main(vararg args: String) {
            val sheetName = args[0]
            val a1range = args[1]
            getValuesFromRange("$sheetName!$a1range")
                .let { gson.toJson(it) }
                .let { println(it) }
        }
    }
}
