export const PLAYER_NAMES = [
    "Ja",
    "Ilona",
    "Maciek",
    "Kamil",
    "Łysy",
    "Kofin",
    "Korot",
    "Żulian",
    "Paweł",
    "Ola",
    "Lamdziadek",
    "Wujor",
    "Mona",
    "Dawid",
    "Kasia Tricamp",
    "Ola Tricamp",
    "Gosia",
    "Rafał",
    "Kuba",
    "Anastazja",
    "Automa",
]

export const GAME_NAMES = [
    "7 cudów Pojedynek",
    "7 cudów świata",
    "Azul",
    "Blood Rage",
    "Brass",
    "Caverna",
    "Cyklady",
    "Everdell",
    "Kości",
    "Welcome To",
    "Kolejowy Szlak",
    "Race for the Galaxy",
    "Res Arcana",
    "Root",
    "Terraformacja",
    "This War of Mine",
    "Agricola",
    "Diuna Imperium",
    "Arnak",
    "Mur Hadriana",
    "Botanik",
    "Projekt L",
    "Gloomhaven",
    "Załoga Głębiny",
    "Summoner Wars",
    "Scythe",
    "Aeons End",
    "Kaskadia",
    "Great Western Trail",
    "O mój Zboże",
    "Brzdęk",
]